<?php

use Illuminate\Database\Seeder;
use App\Standard;
use App\FocusArea;

class StandardsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * @return void
     */
    public function run()
    {
        # Array of standard data to add
        //Todo: add display order? Fix Training from Absolute to minimum
        //Todo: Reverse the ranking in the excel spreadsheet
        $standards = [
            ['i1.1.1', 'Total Inbound Volume', 0, 1, 0, 0, '', 0, 'Inbound Informational Calls'],
            ['i1.1.2', 'Agent Handled Volume', 0, 1, 0, 0, '', 0, 'Inbound Informational Calls'],
            ['i1.1.3', 'Informational IVR Volume', 0, 1, 0, 0, '', 0, 'Inbound Informational Calls'],
            ['i1.1.4', 'Informational IVR Percentage', 0, 1, 0, 0, '%', 0, 'Inbound Informational Calls'],
            ['i1.1.5', 'Abandoned  Volume', 0, 1, 0, 0, '', 0, 'Inbound Informational Calls'],
            ['i1.1.6', 'Abandoned Percentage', 0, 1, 0, 0, '%', 0, 'Inbound Informational Calls'],
            ['S1.1.1', 'Max Interval Abandon Rate', 1, 3, 0, 8, '%', 6, 'Inbound Informational Calls'],
            ['i1.1.7', 'Average Time to Abandon', 0, 1, 0, 0, 'secs', 0, 'Inbound Informational Calls'],
            ['i1.1.8', 'Max Delay', 0, 1, 0, 0, 'secs', 0, 'Inbound Informational Calls'],
            ['S1.1.2', 'Service Level', 1, 2, 85, 90, '%', 2, 'Inbound Informational Calls'],
            ['S1.1.3', 'Average Handle Time', 1, 2, 60, 90, 'secs', 6, 'Inbound Informational Calls'],
            ['S1.1.4', 'Short Calls Percentage', 1, 3, 0, 10, '%', 7, 'Inbound Informational Calls'],
            ['S1.1.5', 'Long Calls Percentage', 1, 3, 0, 5, '%', 7, 'Inbound Informational Calls'],
            ['S1.1.6', 'Holds Per Call', 1, 3, 0, 10, '%', 6, 'Inbound Informational Calls'],
            ['S1.1.7', 'Hold Duration', 1, 3, 0, 30, 'secs', 6, 'Inbound Informational Calls'],
            ['S1.1.8', 'First Call Resolution', 1, 1, 95, 0, '%', 4, 'Inbound Informational Calls'],
            ['S1.1.9', 'Re-directed Calls Percentage', 1, 3, 0, 5, '%', 3, 'Inbound Informational Calls'],
            ['S1.1.10', 'All Trunks Busy', 1, 3, 0, 100, 'mins', 7, 'Inbound Informational Calls'],
            ['S1.1.11', 'QA Score', 1, 1, 90, 0, '%', 2, 'Inbound Informational Calls'],
            ['S1.1.12', 'Customer Effort Score', 1, 1, 9, 0, '', 1, 'Inbound Informational Calls'],
            ['S1.1.13', 'CSAT Score', 1, 1, 8, 0, '', 2, 'Inbound Informational Calls'],
            ['i1.1.9', 'Net Promoter Score', 0, 1, 0, 0, '', 0, 'Inbound Informational Calls'],
            ['i1.2.1', 'Total Inbound  Volume', 0, 1, 0, 0, '', 0, 'Inbound Transactional Calls'],
            ['i1.2.2', 'Agent Handled Volume', 0, 1, 0, 0, '', 0, 'Inbound Transactional Calls'],
            ['i1.2.3', 'Transactional IVR Volume', 0, 1, 0, 0, '', 0, 'Inbound Transactional Calls'],
            ['i1.2.4', 'Transactional IVR Percentage', 0, 1, 0, 0, '%', 0, 'Inbound Transactional Calls'],
            ['i1.2.5', 'Abandoned Volume', 0, 1, 0, 0, '', 0, 'Inbound Transactional Calls'],
            ['i1.2.6', 'Abandoned Percentage', 0, 1, 0, 0, '%', 0, 'Inbound Transactional Calls'],
            ['S1.2.1', 'Max Interval Abandon Rate', 1, 3, 0, 8, '%', 2, 'Inbound Transactional Calls'],
            ['i1.2.7', 'Average Time to Abandon', 0, 1, 0, 0, 'secs', 0, 'Inbound Transactional Calls'],
            ['i1.2.8', 'Max Delay', 0, 1, 0, 0, '', 0, 'Inbound Transactional Calls'],
            ['S1.2.2', 'Service Level', 1, 2, 75, 85, '%', 2, 'Inbound Transactional Calls'],
            ['S1.2.3', 'Average Handle Time', 1, 2, 120, 240, 'secs', 6, 'Inbound Transactional Calls'],
            ['S1.2.4', 'Short Calls Percentage', 1, 3, 0, 10, '%', 7, 'Inbound Transactional Calls'],
            ['S1.2.5', 'Long Calls Percentage', 1, 3, 0, 5, '%', 7, 'Inbound Transactional Calls'],
            ['S1.2.6', 'Holds Per Call', 1, 3, 0, 20, '%', 6, 'Inbound Transactional Calls'],
            ['S1.2.7', 'Hold Duration', 1, 3, 0, 45, 'secs', 6, 'Inbound Transactional Calls'],
            ['S1.2.8', 'First Call Resolution', 1, 1, 80, 0, '%', 4, 'Inbound Transactional Calls'],
            ['S1.2.9', 'Re-directed Calls Percentage', 1, 3, 0, 15, '%', 3, 'Inbound Transactional Calls'],
            ['S1.2.10', 'All Trunks Busy', 1, 3, 0, 100, 'mins', 7, 'Inbound Transactional Calls'],
            ['S1.2.11', 'QA Score', 1, 1, 90, 0, '%', 2, 'Inbound Transactional Calls'],
            ['S1.2.12', 'Customer Effort Score', 1, 1, 8, 0, '', 1, 'Inbound Transactional Calls'],
            ['S1.2.13', 'CSAT Score', 1, 1, 8, 0, '', 2, 'Inbound Transactional Calls'],
            ['i1.2.9', 'Net Promoter Score', 0, 1, 0, 0, '', 0, 'Inbound Transactional Calls'],
            ['i1.3.1', 'Outbound Attempts Volume', 0, 1, 0, 0, '', 0, 'Outbound Calls'],
            ['i1.3.2', 'Outbound Busy Volume', 0, 1, 0, 0, '', 0, 'Outbound Calls'],
            ['i1.3.3', 'Outbound Answered Volume', 0, 1, 0, 0, '', 0, 'Outbound Calls'],
            ['i1.3.4', 'Outbound Connected Volume', 0, 1, 0, 0, '', 0, 'Outbound Calls'],
            ['S1.3.1', 'Average Handle Time', 1, 2, 90, 120, 'secs', 3, 'Outbound Calls'],
            ['S1.3.2', 'Short Calls Percentage', 1, 3, 0, 15, '%', 4, 'Outbound Calls'],
            ['i1.3.5', 'Long Calls Percentage', 0, 1, 0, 0, '%', 0, 'Outbound Calls'],
            ['S1.3.3', 'Holds Per Call', 1, 3, 0, 10, '%', 2, 'Outbound Calls'],
            ['S1.3.4', 'Hold Duration', 1, 3, 0, 30, 'secs', 2, 'Outbound Calls'],
            ['S1.3.5', 'QA Score', 1, 1, 90, 0, '%', 1, 'Outbound Calls'],
            ['i1.4.1', 'Received Email Volume', 0, 1, 0, 0, '', 0, 'Email'],
            ['i1.4.2', 'Handled Email Volume', 0, 1, 0, 0, '', 0, 'Email'],
            ['i1.4.3', 'Automatically Handled Email Volume', 0, 1, 0, 0, '', 0, 'Email'],
            ['i1.4.4', 'Repeat Email from Auto Response', 0, 1, 0, 0, '%', 0, 'Email'],
            ['S1.4.1', 'Repeat Email from Manual Response', 1, 3, 0, 10, '%', 4, 'Email'],
            ['S1.4.2', 'Average Handle Time', 1, 2, 120, 300, 'secs', 4, 'Email'],
            ['S1.4.3', 'Average Response Time', 1, 2, 3.5, 4.5, 'hrs', 3, 'Email'],
            ['S1.4.4', 'Re-directed Email Percentage', 1, 3, 0, 5, '%', 2, 'Email'],
            ['S1.4.5', 'QA Score', 1, 1, 90, 0, '%', 2, 'Email'],
            ['S1.4.6', 'Customer Effort Score', 1, 1, 9, 0, '', 1, 'Email'],
            ['S1.4.7', 'CSAT Score', 1, 1, 8, 0, '', 2, 'Email'],
            ['i1.4.5', 'Net Promoter Score', 0, 1, 0, 0, '', 0, 'Email'],
            ['i1.5.1', 'Total Chat Volume', 0, 1, 0, 0, '', 0, 'Chat / WhatsApp'],
            ['i1.5.2', 'Abandoned Chat Volume', 0, 1, 0, 0, '', 0, 'Chat / WhatsApp'],
            ['i1.5.3', 'Abandoned Chat Percentage', 0, 1, 0, 0, '%', 0, 'Chat / WhatsApp'],
            ['S1.5.1', 'Max Interval Abandon Rate', 1, 3, 0, 8, '%', 6, 'Chat / WhatsApp'],
            ['i1.5.4', 'Average Time to Abandon', 0, 1, 0, 0, 'secs', 0, 'Chat / WhatsApp'],
            ['S1.5.2', 'Service Level', 1, 2, 85, 90, '%', 2, 'Chat / WhatsApp'],
            ['i1.5.5', 'Max Chat Delay', 0, 1, 0, 0, 'secs', 0, 'Chat / WhatsApp'],
            ['S1.5.3', 'Average Handle Time', 1, 2, 240, 480, 'secs', 5, 'Chat / WhatsApp'],
            ['S1.5.4', 'First Chat Resolution', 1, 1, 85, 0, '%', 4, 'Chat / WhatsApp'],
            ['S1.5.5', 'Re-directed Chat Percentage', 1, 3, 0, 20, '%', 3, 'Chat / WhatsApp'],
            ['S1.5.6', 'Max Simultaneous Sessions per Agent', 1, 2, 3, 6, '', 5, 'Chat / WhatsApp'],
            ['S1.5.7', 'QA Score', 1, 1, 95, 0, '%', 2, 'Chat / WhatsApp'],
            ['S1.5.8', 'Customer Effort Score', 1, 1, 9, 0, '', 1, 'Chat / WhatsApp'],
            ['S1.5.9', 'CSAT Score', 1, 1, 8, 0, '', 2, 'Chat / WhatsApp'],
            ['i1.5.6', 'Net Promoter Score', 0, 1, 0, 0, '', 0, 'Chat / WhatsApp'],
            ['i1.6.1', 'Received SMS Volume', 0, 1, 0, 0, '', 0, 'SMS'],
            ['i1.6.2', 'Handled SMS Volume', 0, 1, 0, 0, '', 0, 'SMS'],
            ['i1.6.3', 'Automatically Handled SMS Percentage', 0, 1, 0, 0, '%', 0, 'SMS'],
            ['i1.6.4', 'Repeat SMS from Auto Response', 0, 1, 0, 0, '%', 0, 'SMS'],
            ['S1.6.1', 'Repeat SMS from Manual Response', 1, 3, 0, 10, '%', 4, 'SMS'],
            ['S1.6.2', 'Average SMS Response Time', 1, 3, 0, 10, 'mins', 2, 'SMS'],
            ['S1.6.3', 'Average Handle Time - Manual SMS', 1, 2, 60, 90, 'secs', 4, 'SMS'],
            ['S1.6.4', 'Re-directed SMS Percentage', 1, 3, 0, 5, '%', 3, 'SMS'],
            ['S1.6.5', 'QA Score', 1, 1, 95, 0, '%', 2, 'SMS'],
            ['S1.6.6', 'Customer Effort Score', 1, 1, 9, 0, '', 1, 'SMS'],
            ['S1.6.7', 'CSAT Score', 1, 1, 8, 0, '', 2, 'SMS'],
            ['i1.6.5', 'Net Promoter Score', 0, 1, 0, 0, '', 0, 'SMS'],
            ['i1.7.1', 'SocMed Handled Volume', 0, 1, 0, 0, '', 0, 'Social Media'],
            ['S1.7.1', 'Average Response Time', 1, 3, 0, 8, 'hrs', 3, 'Social Media'],
            ['S1.7.2', 'QA Score', 1, 1, 95, 0, '%', 2, 'Social Media'],
            ['S1.7.3', 'Customer Effort Score', 1, 1, 8.5, 0, '', 1, 'Social Media'],
            ['S1.7.4', 'CSAT Score', 1, 1, 8, 0, '', 2, 'Social Media'],
            ['i1.7.2', 'Net Promoter Score', 0, 1, 0, 0, '', 0, 'Social Media'],
            ['i1.8.1', 'Informational IVR Volume', 0, 1, 0, 0, '', 0, 'Informational IVR'],
            ['i1.8.2', 'Informational IVR Percentage', 0, 1, 0, 0, '%', 0, 'Informational IVR'],
            ['i1.8.3', 'Abandoned Informational IVR Volume', 0, 1, 0, 0, '', 0, 'Informational IVR'],
            ['i1.8.4', 'Abandoned Informational IVR Percentage', 0, 1, 0, 0, '%', 0, 'Informational IVR'],
            ['S1.8.1', 'Max Interval Abandon Rate', 1, 3, 0, 3, '%', 4, 'Informational IVR'],
            ['S1.8.2', 'All Channels Busy', 1, 3, 0, 50, 'mins', 5, 'Informational IVR'],
            ['S1.8.3', 'Percentage of Info IVR Calls Transferred to Agent', 1, 3, 0, 20, '%', 2, 'Informational IVR'],
            ['S1.8.4', 'Average Info IVR Time (Fully Resolved)', 1, 3, 0, 120, 'secs', 3, 'Informational IVR'],
            ['i1.8.5', 'Average Info IVR Time (Transferred To Agent)', 0, 1, 0, 0, 'secs', 0, 'Informational IVR'],
            ['i1.8.6', 'Average Info IVR Time (Abandoned)', 0, 1, 0, 0, 'secs', 0, 'Informational IVR'],
            ['S1.8.5', 'Max Number of Menu "Levels"', 1, 3, 0, 4, '', 3, 'Informational IVR'],
            ['S1.8.6', 'Max Number of Options Per Menu', 1, 3, 0, 4, '', 3, 'Informational IVR'],
            ['S1.8.7', 'Informational IVR Languages', 1, 1, 2, 0, '', 2, 'Informational IVR'],
            ['S1.8.8', 'QA Score', 1, 1, 90, 0, '%', 1, 'Informational IVR'],
            ['S1.8.9', 'Customer Effort Score', 1, 1, 9, 0, '', 1, 'Informational IVR'],
            ['i1.8.7', 'Net Promoter Score', 0, 1, 0, 0, '', 0, 'Informational IVR'],
            ['i1.9.1', 'Transactional IVR Volume', 0, 1, 0, 0, '', 0, 'Transactional IVR'],
            ['i1.9.2', 'Transactional IVR Percentage', 0, 1, 0, 0, '%', 0, 'Transactional IVR'],
            ['i1.9.3', 'Abandoned Transactional IVR Volume', 0, 1, 0, 0, '', 0, 'Transactional IVR'],
            ['i1.9.4', 'Abandoned Transactional IVR Percentage', 0, 1, 0, 0, '%', 0, 'Transactional IVR'],
            ['S1.9.1', 'Max Interval Abandon Rate', 1, 3, 0, 3, '%', 4, 'Transactional IVR'],
            ['S1.9.2', 'All Channels Busy', 1, 3, 0, 50, 'mins', 5, 'Transactional IVR'],
            ['S1.9.3', 'Percentage of Trans. IVR Calls Transferred to Agent', 1, 3, 0, 30, '%', 2, 'Transactional IVR'],
            ['S1.9.4', 'Average Trans. IVR Time (Fully Resolved)', 1, 3, 0, 180, 'secs', 3, 'Transactional IVR'],
            ['i1.9.5', 'Average Trans. IVR Time (Transferred To Agent)', 0, 1, 0, 0, 'secs', 0, 'Transactional IVR'],
            ['i1.9.6', 'Average Trans. IVR Time (Abandoned)', 0, 1, 0, 0, 'secs', 0, 'Transactional IVR'],
            ['S1.9.5', 'Max Number of Menu "Levels"', 1, 3, 0, 6, '', 3, 'Transactional IVR'],
            ['S1.9.6', 'Max Number of Options Per Menu', 1, 3, 0, 4, '', 3, 'Transactional IVR'],
            ['S1.9.7', 'Transactional IVR Languages', 1, 1, 2, 0, '', 2, 'Transactional IVR'],
            ['S1.9.8', 'Transactional IVR FCR', 1, 1, 60, 0, '%', 1, 'Transactional IVR'],
            ['S1.9.9', ' QA Score', 1, 1, 90, 0, '%', 2, 'Transactional IVR'],
            ['S1.9.10', 'Customer Effort Score', 1, 1, 8, 0, '', 1, 'Transactional IVR'],
            ['i1.9.7', 'Net Promoter Score', 0, 1, 0, 0, '', 0, 'Transactional IVR'],
            ['S2.1.1', 'Understanding GDCCS', 1, 1, 100, 0, '%', 1, 'Agents - Essential Skills'],
            ['S2.1.2', 'Interaction Technology', 1, 1, 100, 0, '%', 1, 'Agents - Essential Skills'],
            ['S2.1.3', 'Team Work', 1, 1, 100, 0, '%', 1, 'Agents - Essential Skills'],
            ['S2.1.4', 'Essential Customer Interaction Skills', 1, 1, 100, 0, '%', 1, 'Agents - Essential Skills'],
            ['S2.1.5', 'Basic Communications Skills', 1, 1, 100, 0, '%', 1, 'Agents - Essential Skills'],
            ['S2.1.6', 'Reactive Interactions Structure & Wording', 1, 1, 100, 0, '%', 1, 'Agents - Essential Skills'],
            ['S2.1.7', 'Customer Service', 1, 1, 100, 0, '%', 1, 'Agents - Essential Skills'],
            ['S2.1.8', 'Questioning and Listening Skills', 1, 1, 100, 0, '%', 1, 'Agents - Essential Skills'],
            ['S2.1.9', 'Building Rapport (NLP)', 1, 1, 100, 0, '%', 1, 'Agents - Essential Skills'],
            ['S2.1.10', 'Dealing with Anger, Irate and Abusive Behaviours', 1, 1, 100, 0, '%', 1, 'Agents - Essential Skills'],
            ['S2.1.11', 'Controlling Customer Interactions', 1, 1, 100, 0, '%', 1, 'Agents - Essential Skills'],
            ['S2.1.12', 'Multi-lingual Challenges', 1, 1, 100, 0, '%', 1, 'Agents - Essential Skills'],
            ['S2.1.13', 'Proactive Interactions Structure, Control & Outcome', 1, 1, 100, 0, '%', 1, 'Agents - Essential Skills'],
            ['S2.1.14', 'Handling Objections', 1, 1, 100, 0, '%', 1, 'Agents - Essential Skills'],
            ['S2.1.15', 'Tele-surveying Skills', 1, 1, 100, 0, '%', 1, 'Agents - Essential Skills'],
            ['S2.1.16', 'Understanding Organisational Performance', 1, 1, 100, 0, '%', 1, 'Agents - Essential Skills'],
            ['S2.1.17', 'Personal Performance Development', 1, 1, 100, 0, '%', 1, 'Agents - Essential Skills'],
            ['S2.1.18', 'Service Recovery Skills', 1, 1, 100, 0, '%', 1, 'Agents - Essential Skills'],
            ['S2.1.19', 'Touchpoint Variances', 1, 1, 100, 0, '%', 1, 'Agents - Essential Skills'],
            ['S2.1.20', 'Multi Touchpoint Technology', 1, 1, 100, 0, '%', 1, 'Agents - Essential Skills'],
            ['S2.1.21', 'How We Think and Understand', 1, 1, 100, 0, '%', 1, 'Agents - Essential Skills'],
            ['S2.1.22', 'Empowered Responsibility', 1, 1, 100, 0, '%', 1, 'Agents - Essential Skills'],
            ['S2.1.23', 'Understanding Customer Experience', 1, 1, 100, 0, '%', 1, 'Agents - Essential Skills'],
            ['S2.1.24', 'Delivering a Branded Experience', 1, 1, 100, 0, '%', 1, 'Agents - Essential Skills'],
            ['S2.1.25', 'Understanding Organisational Experiential Performance', 1, 1, 100, 0, '%', 1, 'Agents - Essential Skills'],
            ['S2.1.26', 'Personal Experiential Performance Development', 1, 1, 100, 0, '%', 1, 'Agents - Essential Skills'],
            ['S2.2.1', 'Challenges of Written Interactions', 1, 1, 100, 0, '%', 1, 'Agents - Written Skills'],
            ['S2.2.2', 'Basics of Written Arabic', 1, 1, 100, 0, '%', 1, 'Agents - Written Skills'],
            ['S2.2.3', 'Basics of Written English', 1, 1, 100, 0, '%', 1, 'Agents - Written Skills'],
            ['S2.3.1', 'Customer Relationship Management', 1, 1, 100, 0, '%', 1, 'Agents - CRM'],
            ['S2.4.1', 'All Applicable Agent Training Courses', 1, 1, 100, 0, '%', 1, 'Team Leaders / Supervisors'],
            ['S2.4.2', 'Understanding KPIs', 1, 1, 100, 0, '%', 1, 'Team Leaders / Supervisors'],
            ['S2.4.3', 'Quality Management', 1, 1, 100, 0, '%', 1, 'Team Leaders / Supervisors'],
            ['S2.4.4', 'Coaching', 1, 1, 100, 0, '%', 1, 'Team Leaders / Supervisors'],
            ['S2.4.5', 'Conflict Management', 1, 1, 100, 0, '%', 1, 'Team Leaders / Supervisors'],
            ['S2.4.6', 'Customer Satisfaction Metrics', 1, 1, 100, 0, '%', 1, 'Team Leaders / Supervisors'],
            ['S2.4.7', 'Resource Planning & Scheduling', 1, 1, 100, 0, '%', 1, 'Team Leaders / Supervisors'],
            ['S2.4.8', 'Performance Management', 1, 1, 100, 0, '%', 1, 'Team Leaders / Supervisors'],
            ['S2.4.9', 'Strategic Leadership', 1, 1, 100, 0, '%', 1, 'Team Leaders / Supervisors'],
            ['S2.4.10', 'Team Building', 1, 1, 100, 0, '%', 1, 'Team Leaders / Supervisors'],
            ['S2.4.11', 'Communications Skills', 1, 1, 100, 0, '%', 1, 'Team Leaders / Supervisors'],
            ['S2.4.12', 'Team Competence Development', 1, 1, 100, 0, '%', 1, 'Team Leaders / Supervisors'],
            ['S2.4.13', 'Team Performance Development', 1, 1, 100, 0, '%', 1, 'Team Leaders / Supervisors'],
            ['S2.4.14', 'Supervisor Technologies', 1, 1, 100, 0, '%', 1, 'Team Leaders / Supervisors'],
            ['S2.4.15', 'Reporting', 1, 1, 100, 0, '%', 1, 'Team Leaders / Supervisors'],
            ['S2.4.16', 'CEM Essentials', 1, 1, 100, 0, '%', 1, 'Team Leaders / Supervisors'],
            ['S2.4.17', 'Voice Of The Customer', 1, 1, 100, 0, '%', 1, 'Team Leaders / Supervisors'],
            ['S2.4.18', 'Understanding Financial Statements', 1, 1, 100, 0, '%', 1, 'Team Leaders / Supervisors'],
            ['S2.4.19', 'Experiential Returns', 1, 1, 100, 0, '%', 1, 'Team Leaders / Supervisors'],
            ['S2.4.20', 'Staff Experience Management', 1, 1, 100, 0, '%', 1, 'Team Leaders / Supervisors'],
            ['S2.4.21', 'Motivation & Stress Management', 1, 1, 100, 0, '%', 1, 'Team Leaders / Supervisors'],
            ['S2.4.22', 'Managing Difficult Team Members', 1, 1, 100, 0, '%', 1, 'Team Leaders / Supervisors'],
            ['S2.4.23', 'Presentation Skills', 1, 1, 100, 0, '%', 1, 'Team Leaders / Supervisors'],
            ['S2.4.24', 'Understanding Organisational Experiential Performance', 1, 1, 100, 0, '%', 1, 'Team Leaders / Supervisors'],
            ['S2.4.25', 'Personal Experiential Performance Development', 1, 1, 100, 0, '%', 1, 'Team Leaders / Supervisors'],
            ['S2.5.1', 'All Applicable Agent Courses', 1, 1, 100, 0, '%', 1, 'OSF Staff'],
            ['S2.5.2', 'Recommended Courses as per OSF Standards', 1, 1, 100, 0, '%', 1, 'OSF Staff'],
            ['S2.6.1', 'All Applicable Supervisory Courses', 1, 1, 100, 0, '%', 1, 'Management'],
            ['S2.6.2', 'Recommended Courses as per PCS', 1, 1, 100, 0, '%', 1, 'Management'],
            ['S2.7.1', 'Attendance', 1, 1, 95, 0, ' % ', 1, 'Agent Performance'],
            ['S2.7.2', 'Adherence', 1, 1, 92, 0, ' % ', 1, 'Agent Performance'],
            ['S2.7.3', 'Occupancy', 1, 2, 75, 90, ' % ', 2, 'Agent Performance'],
            ['S2.7.4', 'Shrinkage', 1, 3, 0, 25, ' % ', 4, 'Agent Performance'],
            ['S2.7.5', 'Quiz Average', 1, 1, 95, 0, ' % ', 3, 'Agent Performance'],
            ['S2.7.6', 'QA Score', 1, 1, 90, 0, ' % ', 2, 'Agent Performance'],
            ['S2.7.7', 'CSAT Score', 1, 1, 8, 0, '', 3, 'Agent Performance'],
            ['i2.7.1', 'ESAT Score', 0, 1, 0, 0, '', 0, 'Agent Performance'],
            ['i2.7.2', 'QAS Delta', 0, 1, 0, 0, '', 0, 'Agent Performance'],
            ['S2.8.1', 'Attendance', 1, 1, 95, 0, ' % ', 1, 'TL and Supervisor Performance'],
            ['S2.8.2', 'Adherence', 1, 1, 92, 0, ' % ', 1, 'TL and Supervisor Performance'],
            ['S2.8.3', 'Occupancy', 1, 2, 75, 90, ' % ', 3, 'TL and Supervisor Performance'],
            ['i2.8.1', 'Shrinkage', 0, 1, 0, 0, ' % ', 0, 'TL and Supervisor Performance'],
            ['S2.8.4', 'Quiz Average', 1, 1, 95, 0, ' % ', 3, 'TL and Supervisor Performance'],
            ['S2.8.5', 'QA Score', 1, 1, 90, 0, ' % ', 2, 'TL and Supervisor Performance'],
            ['i2.8.2', 'CSAT Score', 0, 1, 0, 0, '', 0, 'TL and Supervisor Performance'],
            ['i2.8.3', 'ESAT Score', 0, 1, 0, 0, '', 0, 'TL and Supervisor Performance'],
            ['i2.8.4', 'QAS Delta', 0, 1, 0, 0, '', 0, 'TL and Supervisor Performance'],
            ['S3.1.1', 'Interactions Recorded for Random Analysis', 1, 0, 0, 0, '', 1, 'Quality Assurance'],
            ['S3.1.2', 'Sufficient QA Analysts', 1, 0, 0, 0, '', 2, 'Quality Assurance'],
            ['S3.1.3', 'QA Staff OSP Management Certification', 1, 0, 0, 0, '', 2, 'Quality Assurance'],
            ['S3.1.4', 'Valid QA Sample Size', 1, 0, 0, 0, '', 2, 'Quality Assurance'],
            ['S3.1.5', 'GDCCS Interaction Scorecard Utilised', 1, 0, 0, 0, '', 2, 'Quality Assurance'],
            ['S3.1.6', 'Management of Monthly Quiz', 1, 0, 0, 0, '', 4, 'Quality Assurance'],
            ['S3.1.7', 'CEM Canvas Analysis', 1, 0, 0, 0, '', 3, 'Quality Assurance'],
            ['S3.1.8', 'Attitudinal(NPS) Correlations to Perceptions(CSAT)', 1, 0, 0, 0, '', 2, 'Quality Assurance'],
            ['S3.1.9', 'Validation Calls with Customers', 1, 2, 10, 20, ' % ', 4, 'Quality Assurance'],
            ['S3.1.10', 'QA Auto Calibration Techniques Deployed', 1, 0, 0, 0, '', 6, 'Quality Assurance'],
            ['S3.1.11', 'Double - Blind Analyses', 1, 2, 10, 15, ' % ', 3, 'Quality Assurance'],
            ['S3.1.12', 'Monthly QA & KPI Performance Reports', 1, 0, 0, 0, '', 4, 'Quality Assurance'],
            ['S3.1.13', 'Team / Operations Performance Reports', 1, 0, 0, 0, '', 4, 'Quality Assurance'],
            ['S3.1.14', 'Integrated Service Recovery Process ', 1, 0, 0, 0, '', 3, 'Quality Assurance'],
            ['S3.1.15', 'Average Deviation of Validated Analyses', 1, 3, 0, 33, ' % ', 4, 'Quality Assurance'],
            ['S3.1.16', 'Average Deviation of Double - Blind Analyses', 1, 3, 0, 15, ' % ', 3, 'Quality Assurance'],
            ['S3.1.17', 'Attendance', 1, 1, 95, 0, ' % ', 3, 'Quality Assurance'],
            ['S3.1.18', 'Adherence', 1, 1, 92, 0, ' % ', 4, 'Quality Assurance'],
            ['S3.1.19', 'Quiz Average', 1, 1, 100, 0, ' % ', 4, 'Quality Assurance'],
            ['S3.2.1', 'Sufficient WFM Resources', 1, 0, 0, 0, '', 1, 'Workforce Management'],
            ['S3.2.2', 'Certified WFM Staff', 1, 0, 0, 0, '', 2, 'Workforce Management'],
            ['S3.2.3', 'Remote Touchpoint System Data Capture Intervals', 1, 2, 15, 30, 'mins', 2, 'Workforce Management'],
            ['S3.2.4', 'Statistical Volume Forecasting', 1, 0, 0, 0, '', 2, 'Workforce Management'],
            ['S3.2.5', 'Volume Forecast Adjusted for Seasonality', 1, 0, 0, 0, '', 2, 'Workforce Management'],
            ['S3.2.6', 'Volume Forecast Adjusted for Affecting Events', 1, 0, 0, 0, '', 4, 'Workforce Management'],
            ['S3.2.7', 'Monthly Volume Forecast Accuracy', 1, 1, 90, 0, ' % ', 3, 'Workforce Management'],
            ['S3.2.8', 'Agent Resource Calculations', 1, 0, 0, 0, '', 2, 'Workforce Management'],
            ['S3.2.9', 'Agent Resource Calculations Adjustment', 1, 0, 0, 0, '', 4, 'Workforce Management'],
            ['S3.2.10', 'Real Time Schedule Adjustments', 1, 0, 0, 0, '', 6, 'Workforce Management'],
            ['S3.2.11', 'Backup Plans for Unanticipated High Workload or Service Levels Failures', 1, 0, 0, 0, '', 4, 'Workforce Management'],
            ['S3.2.12', 'Attendance', 1, 1, 95, 0, ' % ', 3, 'Workforce Management'],
            ['S3.2.13', 'Adherence', 1, 1, 92, 0, ' % ', 2, 'Workforce Management'],
            ['S3.3.1', 'Real Time Wallboards or Dashboards', 1, 1, 1, 0, '', 1, 'Real-time WFM'],
            ['S3.3.2', 'Disaster Recovery Plan with Backup Resources', 1, 0, 0, 0, '', 1, 'Real-time WFM'],
            ['S3.3.3', 'Disaster Recovery Plan with Live Re-skilling', 1, 0, 0, 0, '', 1, 'Real-time WFM'],
            ['S3.3.4', 'Intra-day Volume Forecast Frequency', 1, 3, 0, 120, 'mins', 1, 'Real-time WFM'],
            ['S3.3.5', 'Escalation Process for Excessive Attendance or Adherence Failures', 1, 0, 0, 0, '', 1, 'Real-time WFM'],
            ['S3.4.1', 'Assessment Team Certification', 1, 0, 0, 0, '', 5, 'Recruitment'],
            ['S3.4.2', 'CV Evaluation', 1, 0, 0, 0, '', 5, 'Recruitment'],
            ['S3.4.3', 'Telephone / Chat Interview', 1, 0, 0, 0, '', 7, 'Recruitment'],
            ['S3.4.4', 'Interaction Skills', 1, 0, 0, 0, '', 7, 'Recruitment'],
            ['S3.4.5', 'Computer Skills', 1, 0, 0, 0, '', 7, 'Recruitment'],
            ['S3.4.6', 'Language Skills ', 1, 0, 0, 0, '', 7, 'Recruitment'],
            ['S3.4.7', 'Teamwork Skills', 1, 0, 0, 0, '', 7, 'Recruitment'],
            ['S3.4.8', 'Multitasking Skills', 1, 0, 0, 0, '', 7, 'Recruitment'],
            ['S3.4.9', 'Interaction Management Skills', 1, 0, 0, 0, '', 6, 'Recruitment'],
            ['S3.4.10', 'Numeric Skills', 1, 0, 0, 0, '', 6, 'Recruitment'],
            ['S3.4.11', 'Customer Service Attitude', 1, 0, 0, 0, '', 2, 'Recruitment'],
            ['S3.4.12', 'Assessment Protocols', 1, 0, 0, 0, '', 1, 'Recruitment'],
            ['S3.4.13', 'Multiple Assessors per Candidate', 1, 0, 0, 0, '', 6, 'Recruitment'],
            ['S3.4.14', 'Hiring on Proven Merit', 1, 0, 0, 0, '', 1, 'Recruitment'],
            ['S3.4.15', 'Transparent Decision Process', 1, 0, 0, 0, '', 6, 'Recruitment'],
            ['i3.4.1', 'CVs Evaluated per Telephone or Chat Interviewee',0,1,0,0,'',0,'Recruitment'],
            ['i3.4.2', 'Telephone or Chat Interviews per Assessment Centre Invitee', 0, 1, 0, 0, '', 0, 'Recruitment'],
            ['i3.4.3', 'Assessment Centre Invitees per Offer', 0, 1, 0, 0, '', 0, 'Recruitment'],
            ['i3.4.4', 'Offers per Recruit', 0, 1, 0, 0, '', 0, 'Recruitment'],
            ['i3.4.5', 'Recruit Retention', 0, 1, 0, 0, ' % ', 0, 'Recruitment'],
            ['S3.5.1', 'Licensed and Certified Material', 1, 0, 0, 0, '', 4, 'Training'],
            ['S3.5.2', 'Licensed and Certified Trainers', 1, 0, 0, 0, '', 5, 'Training'],
            ['S3.5.3', 'Role Play Training', 1, 0, 0, 0, '', 7, 'Training'],
            ['S3.5.4', 'ILT & CBT Training Program', 1, 0, 0, 0, '', 7, 'Training'],
            ['S3.5.5', 'Randomised Online Testing', 1, 0, 0, 0, '', 7, 'Training'],
            ['S3.5.6', 'Mentorship', 1, 0, 0, 0, '', 7, 'Training'],
            ['S3.5.7', 'Average Agent Coaching Time', 1, 1, 30, 0, 'mins', 7, 'Training'],
            ['S3.5.8', 'Certified Coaches', 1, 0, 0, 0, '', 3, 'Training'],
            ['S3.5.9', 'Training Staff Quiz Average', 1, 1, 100, 0, ' % ', 6, 'Training'],
            ['S3.5.10', 'Trainee Nominal Performance Period', 1, 2, 6, 10, 'months', 6, 'Training'],
            ['S3.6.1', 'Training', 1, 0, 0, 0, '', 1, 'Complaint Handling'],
            ['S3.6.2', 'Structured Complaint Form', 1, 0, 0, 0, '', 1, 'Complaint Handling'],
            ['S3.6.3', 'Complaint Reference Number', 1, 0, 0, 0, '', 7, 'Complaint Handling'],
            ['S3.6.4', 'Non - interaction Complaints Escalation Process', 1, 0, 0, 0, '', 7, 'Complaint Handling'],
            ['S3.6.5', 'Complaint Investigation Feedback', 1, 0, 0, 0, '', 7, 'Complaint Handling'],
            ['S3.6.6', 'Agent Sanctions ', 1, 0, 0, 0, '', 5, 'Complaint Handling'],
            ['S3.6.7', 'QA Analyst Sanctions', 1, 0, 0, 0, '', 6, 'Complaint Handling'],
            ['S3.6.8', 'Closed Complaint Customer Survey', 1, 1, 25, 0, ' % ', 6, 'Complaint Handling'],
            ['S3.6.9', 'Integrated with QA and Service Recovery Process', 1, 0, 0, 0, '', 2, 'Complaint Handling'],
            ['S3.7.1', 'Secure Server Room', 1, 0, 0, 0, '', 1, 'Disaster Recovery'],
            ['S3.7.2', 'IT Systems Failure Processes', 1, 0, 0, 0, '', 2, 'Disaster Recovery'],
            ['S3.7.3', 'Network or Connectivity Failure Processes', 1, 0, 0, 0, '', 3, 'Disaster Recovery'],
            ['S3.7.4', 'Unusable or Inaccessible Facilities Processes', 1, 0, 0, 0, '', 4, 'Disaster Recovery'],
            ['S3.7.5', 'Processes for Staff Mobility Issues', 1, 0, 0, 0, '', 5, 'Disaster Recovery'],
            ['S3.7.6', 'On - site Resilience and Multiple - site or Off - site Backups', 1, 0, 0, 0, '', 6, 'Disaster Recovery'],
            ['S3.8.1', 'Staff Motivational Budget', 1, 1, 2, 0, ' % ', 1, 'Motivation'],
            ['S3.8.2', 'Internal Recreation Room', 1, 0, 0, 0, '', 5, 'Motivation'],
            ['S3.8.3', 'Customer Interaction Team Gatherings', 1, 0, 0, 0, '', 7, 'Motivation'],
            ['S3.9.1', 'Employee Density', 1, 2, 9, 14, 'm2', 1, 'Staff Facilities'],
            ['S3.9.2', 'Agents Per Workstation', 1, 3, 0, 4, '', 1, 'Staff Facilities'],
            ['S3.9.3', 'Water Coolers', 1, 1, 2, 0, ' % ', 1, 'Staff Facilities'],
            ['S3.9.4', 'Agent Workstation Area', 1, 2, 3, 5, 'm2', 2, 'Staff Facilities'],
            ['S3.9.5', 'Number Of Fire Drills', 1, 2, 4, 12, '', 4, 'Staff Facilities'],
            ['S3.9.6', 'Canteen Hours', 1, 1, 90, 0, ' % ', 4, 'Staff Facilities'],
            ['S3.9.7', 'Canteen Seating Capacity', 1, 1, 5, 0, ' % ', 5, 'Staff Facilities'],
            ['S3.9.8', 'Window to Floor Area Ratio', 1, 1, 12, 0, ' % ', 5, 'Staff Facilities'],
            ['S3.9.9', 'Training Room', 1, 1, 1, 0, '', 6, 'Staff Facilities'],
            ['S3.9.10', 'Concurrent Training Places Available', 1, 1, 10, 0, '', 6, 'Staff Facilities'],
            ['S3.9.11', 'Breakout Areas', 1, 1, 1, 0, '', 7, 'Staff Facilities'],
            ['S3.9.12', 'Breakout Area Ratio', 1, 1, 20, 0, ' % ', 7, 'Staff Facilities'],
            ['S3.9.13', 'Meeting Rooms', 1, 1, 1, 0, '', 7, 'Staff Facilities'],
            ['S3.9.14', 'Meeting Rooms Area Ratio', 1, 1, 20, 0, ' % ', 7, 'Staff Facilities'],
            ['S3.9.15', 'Dedicated QA Area', 1, 1, 1, 0, '', 7, 'Staff Facilities'],
            ['S3.9.16', 'Indoor Recreational Space Floor Area', 1, 1, 10, 0, ' % ', 7, 'Staff Facilities'],
            ['S3.9.17', 'Performance Dashboards', 1, 1, 2, 0, ' % ', 8, 'Staff Facilities'],
            ['i3.9.1', 'Total Floor Area', 0, 1, 0, 0, 'm2', 0, 'Staff Facilities'],
            ['i3.9.2', 'Total Area Of Dedicated QA Operations', 0, 1, 0, 0, 'm2', 0, 'Staff Facilities'],
            ['i3.9.3', 'Team Leader / Super Sits With Their team', 0, 0, 0, 0, '', 0, 'Staff Facilities'],
            ['i3.9.4', 'Outdoor Recreational Space Ratio', 0, 1, 0, 0, ' % ', 0, 'Staff Facilities'],
            ['i3.9.5', 'Operational Hours', 0, 1, 0, 0, 'hrs', 0, 'Staff Facilities'],
            ['i3.9.6', 'Local H & S Rules / Labour Rules', 0, 0, 0, 0, '', 0, 'Staff Facilities'],
            ['i3.9.7', 'Health & Safety Documentation', 0, 0, 0, 0, '', 0, 'Staff Facilities'],
            ['S3.10.1', 'UPS Support Time', 1, 1, 20, 0, 'mins', 1, 'Disaster Recovery / Continuity'],
            ['S3.10.2', 'Emergency Lighting', 1, 0, 0, 0, '', 1, 'Disaster Recovery / Continuity'],
            ['S3.10.3', 'Dedicated Computer Room', 1, 0, 0, 0, '', 1, 'Disaster Recovery / Continuity'],
            ['S3.10.4', 'Computer Room Secure Access System', 1, 0, 0, 0, '', 2, 'Disaster Recovery / Continuity'],
            ['S3.10.5', 'Computer Room Fire Suppression', 1, 0, 0, 0, '', 2, 'Disaster Recovery / Continuity'],
            ['S3.10.6', 'Redundant Servers and PSUs', 1, 0, 0, 0, '', 2, 'Disaster Recovery / Continuity'],
            ['S3.10.7', 'Diverse Datacom Network', 1, 0, 0, 0, '', 3, 'Disaster Recovery / Continuity'],
            ['S3.10.8', 'Separate Site Redundancy', 1, 0, 0, 0, '', 4, 'Disaster Recovery / Continuity'],
            ['S3.10.9', 'Power Backup Generator', 1, 0, 0, 0, '', 4, 'Disaster Recovery / Continuity'],
            ['i3.10.1', 'Multi - site Operational Backup', 0, 0, 0, 0, '', 0, 'Disaster Recovery / Continuity'],
            ['i3.10.2', 'Dark Site Backup', 0, 0, 0, 0, '', 0, 'Disaster Recovery / Continuity'],
            ['S4.1.1', 'Recovery Mode Time', 1, 3, 0, 90, 'mins', 1, 'Contact Centre Technology'],
            ['S4.1.2', 'Shutdown Time', 1, 3, 0, 30, 'mins', 1, 'Contact Centre Technology'],
            ['S4.1.3', 'Telephone System Uptime', 1, 1, 99, 0, ' % ', 2, 'Contact Centre Technology'],
            ['S4.1.4', 'Fulfilment Apps Uptime', 1, 1, 99, 0, ' % ', 2, 'Contact Centre Technology'],
            ['S4.1.5', 'No . Of Fulfilment Apps', 1, 3, 0, 3, '', 3, 'Contact Centre Technology'],
            ['S4.1.6', 'Dashboard Uptime', 1, 1, 99, 0, ' % ', 4, 'Contact Centre Technology'],
            ['S4.1.7', 'Headset Uptime', 1, 1, 99, 0, ' % ', 4, 'Contact Centre Technology'],
            ['S4.1.8', 'Trunk Utilisation', 1, 3, 0, 75, ' % ', 5, 'Contact Centre Technology'],
            ['S4.1.9', 'ERMS Uptime', 1, 1, 99, 0, ' % ', 6, 'Contact Centre Technology'],
            ['S4.1.10', 'Chat System Uptime', 1, 1, 99, 0, ' % ', 7, 'Contact Centre Technology'],
            ['i4.1.1', 'IVR System Uptime', 0, 1, 0, 0, ' % ', 0, 'Contact Centre Technology'],
            ['i4.1.2', 'Call Recording System Uptime', 0, 1, 0, 0, ' % ', 0, 'Contact Centre Technology'],
            ['i4.1.3', 'SMS Gateway Uptime', 0, 1, 0, 0, ' % ', 0, 'Contact Centre Technology'],
            ['i4.1.4', 'WhatsApp Uptime', 0, 1, 0, 0, ' % ', 0, 'Contact Centre Technology'],
            ['i4.1.5', 'Dialer Uptime', 0, 1, 0, 0, ' % ', 0, 'Contact Centre Technology'],
            ['i4.1.6', 'WFM System Uptime', 0, 1, 0, 0, ' % ', 0, 'Contact Centre Technology'],
            ['i4.1.7', 'CTI System Uptime', 0, 1, 0, 0, ' % ', 0, 'Contact Centre Technology'],
        ];
        $count = count($standards);

        //$focus_areas = FocusArea::get();
        //Todo: For every focus area figure out the standard weights
        //foreach ($focus_areas as $focus_area) {
            /*//Find the maximum ranking
            $max_ranking = max(array_column($standards, 7));

            //Reverse the ranking and get the sum
            $rankings_sum = 0;
            foreach ($standards as $standard) {
                //Only look at standards, not indicators
                if ($standard[2] == 1) {
                    $ranking = $max_ranking - $standard[7] + 1;
                    $rankings_sum += $ranking;
                    $ranking_array[] = $ranking;
                }
            }

            foreach ($ranking_array as $ranking) {
                $weight = ((100 / $rankings_sum) * $ranking);
                $weights_array[] = $weight;
            }*/

            # Loop through each standard, adding them to the database
            $index = 0;
            foreach ($standards as $stdData) {
                //$this->command->comment($stdData[0].' '.$stdData[7].' '.$stdData[8]);
                $focusAreaName = $stdData[8];

                # Find the contact center
                $focus_area_id = FocusArea::where('name', '=', $focusAreaName)->pluck('id')->first();
                //$this->command->comment('Focus Area = '.$focusAreaName);
                //$this->command->comment('Focus Area = '.$focus_area_id);

                $standard = new Standard();

                $standard->created_at = Carbon\Carbon::now()->subDays($count)->toDateTimeString();
                $standard->updated_at = Carbon\Carbon::now()->subDays($count)->toDateTimeString();
                $standard->std_num = $stdData[0];
                $standard->name_en = $stdData[1];
                $standard->std_type = $stdData[2];
                $standard->target_type = $stdData[3];
                $standard->target_min = $stdData[4];
                $standard->target_max = $stdData[5];
                $standard->units = $stdData[6];
                $standard->std_ranking = $stdData[7];

/*                if ($standard->std_type == 1) {
                    $standard->weight = $weights_array[$index];
                    $index = $index + 1;
                }*/

                $standard->focus_area_id = $focus_area_id;
                $standard->save();

                $count--;
            }
        //}
    }
}
